### ISSUE TITLE
No functionality to resume from checkpoint

### ISSUE THREAD

**Issue by kaustavmehta** [neural-nuts/image-caption-generator#25] opened 2018-05-23 05:30 UTC
Great work! The model is fantastic! However, I wish to train it upon a very large dataset and I have to stop training in order to test the model (part of an experiment). I find that I cannot resume training from a saved tf.checkpoint; is this a function that I have to code myself or...?

**Comment by DestroPest** [comment] 2018-06-11 11:41
I need the same functionality so save and load checkpoints. Is there a workaround or kaustavmehta, have you implemented the function ?

**Comment by dust0x** [comment] 2018-06-18 07:22
@kaustavmehta cc: @DestroPest 

The functionality exists and is tested. You should be able to resume training using the `--resume` flag in the `train` mode when running `main.py`. 

For example, to run the training on Flickr30k dataset, you should use:

`python main.py --mode train --caption_path ./Dataset/results_20130124.token --feature_path ./Dataset/features.npy --resume`

This will first look for the latest checkpoint and resume training if found, or start training from the beginning otherwise. Can you confirm that it is working for you as intended?

**Comment by dust0x** [comment] 2018-07-14 08:44
Closing: issue is resolved, no further activity from user.

**Closed by dust0x** 2018-07-14 08:44 UTC
