### ISSUE TITLE
TypeError while loading the tokens file

### ISSUE THREAD

**Issue by piyushhajare** [neural-nuts/image-caption-generator#12] opened 2017-12-23 17:18 UTC
Required Files not present. Regenerating Data.
Loading Caption Data Dataset/results_20130124.token
Preprocessing Captions
```
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    config.word_threshold, config.max_len, caption_file, feature_file)
  File "/media/piyush/2EF68783F6874A53/ImageCap/image-caption-generator-master/utils/data_util.py", line 117, in generate_captions
    df = preprocess_captions(filenames, captions)
  File "/media/piyush/2EF68783F6874A53/ImageCap/image-caption-generator-master/utils/data_util.py", line 20, in preprocess_captions
    **df['caption'] = df['caption'].apply(word_tokenize).apply(**
  File "/home/piyush/p3/lib/python3.5/site-packages/pandas/core/series.py", line 2551, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/src/inference.pyx", line 1521, in pandas._libs.lib.map_infer
  File "/home/piyush/p3/lib/python3.5/site-packages/nltk/tokenize/__init__.py", line 128, in word_tokenize
    sentences = [text] if preserve_line else sent_tokenize(text, language)
  File "/home/piyush/p3/lib/python3.5/site-packages/nltk/tokenize/__init__.py", line 95, in sent_tokenize
    return tokenizer.tokenize(text)
  File "/home/piyush/p3/lib/python3.5/site-packages/nltk/tokenize/punkt.py", line 1237, in tokenize
    return list(self.sentences_from_text(text, realign_boundaries))
  File "/home/piyush/p3/lib/python3.5/site-packages/nltk/tokenize/punkt.py", line 1285, in sentences_from_text
    return [text[s:e] for s, e in self.span_tokenize(text, realign_boundaries)]
  File "/home/piyush/p3/lib/python3.5/site-packages/nltk/tokenize/punkt.py", line 1276, in span_tokenize
    return [(sl.start, sl.stop) for sl in slices]
  File "/home/piyush/p3/lib/python3.5/site-packages/nltk/tokenize/punkt.py", line 1276, in <listcomp>
    return [(sl.start, sl.stop) for sl in slices]
  File "/home/piyush/p3/lib/python3.5/site-packages/nltk/tokenize/punkt.py", line 1316, in _realign_boundaries
    for sl1, sl2 in _pair_iter(slices):
  File "/home/piyush/p3/lib/python3.5/site-packages/nltk/tokenize/punkt.py", line 312, in _pair_iter
    prev = next(it)
  File "/home/piyush/p3/lib/python3.5/site-packages/nltk/tokenize/punkt.py", line 1289, in _slices_from_text
    **for match in self._lang_vars.period_context_re().finditer(text):
TypeError: expected string or bytes-like object**
```

**Comment by metalaman** [comment] 2017-12-24 12:06
Check if every caption in **df['caption']** is of type string(and not an empty string). From where did you get _results_20130124.token_? I'll be able to reproduce the error if I have the same file. Also, make sure you remove sentences from _results_20130124.token_ which are just _\n_.

**Comment by metalaman** [comment] 2017-12-31 08:33
@piyushhajare any updates?

**Comment by piyushhajare** [comment] 2017-12-31 08:42
I tried many things but then I realized that there's problem with df.caption.decode('utf').. I HV seen this problem even earlier so I thought to give it a try and so I just commented that line and it somehow worked.
Anyways thanks for your help. I have always been  fascinated by open source community.And yeah sorry for the delay..

**Comment by piyushhajare** [comment] 2017-12-31 08:43
@metalaman Thanks for your help :)

**Comment by dust0x** [comment] 2017-12-31 08:54
The input string was not `utf` encoded in your case so `decode` is unnecessary. I assume this happened for the same reason as #11: the read me has not been updated for the COCO dataset.

@pranay360

**Comment by dust0x** [comment] 2017-12-31 08:58
The input string in the annotation file is not `utf` encoded in your case so `decode` is unnecessary.

@pranay360 is this also because of the differences in usage of COCO and Flickr30k?

**Comment by dust0x** [comment] 2018-01-01 18:29
Closing as the issue was resolved.

**Closed by dust0x** 2018-01-01 18:29 UTC
